name: dynamic

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Value for log level is=>${{inputs.logLevel}}"
